ALTER TABLE public.clients 
ADD COLUMN IF NOT EXISTS target_rate NUMERIC DEFAULT 50,
ADD COLUMN IF NOT EXISTS rate_updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS reengagement_tag TEXT;